No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from config.variant
INFO:conda_build.metadata:Attempting to finalize metadata for r-bayesm
/home/ohnoplus/miniconda3/envs/dada2ab3/conda-bld/r-bayesm_1541209292540/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 439, in main
    execute(sys.argv[1:])
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 430, in execute
    verify=args.verify, variants=args.variants)
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/build.py", line 2275, in build_tree
    notest=notest,
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/build.py", line 1500, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/utils.py", line 319, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/ohnoplus/miniconda3/envs/dada2ab3/lib/python3.6/site-packages/conda_build/utils.py", line 299, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/ohnoplus/miniconda3/envs/dada2ab3/conda-bld/r-bayesm_1541209292540/work/conda_build.sh']' returned non-zero exit status 127.
